Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "Flight Scheduler",
 "business_name" => "My Company, LLC",
 "business_address" => "",
 "domain" => "example.com",
 "support_email" => "support@example.com",
 "default_from_email" => "My App <no-reply@example.com>",
 "background_job_processor" => "sidekiq",
 "email_provider" => "",
 "account_types" => "both",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => [],
 "payment_processors" => ["stripe"],
 "multitenancy" => [],
 "gems" => []})
